window.env = {
  "ALLUSERSPROFILE": "C:\\ProgramData",
  "ANDROID_HOME": "C:\\Users\\Deep1\\AppData\\Local\\Android\\Sdk",
  "api_key": "b98987b2c54cf0ccb98b4691a87115fa",
  "APPDATA": "C:\\Users\\Deep1\\AppData\\Roaming",
  "ChocolateyInstall": "C:\\ProgramData\\chocolatey",
  "ChocolateyLastPathUpdate": "132945193247421969",
  "CHROME_CRASHPAD_PIPE_NAME": "\\\\.\\pipe\\crashpad_12272_OYBEBNJPLWBFMSKY",
  "COLOR": "1",
  "COLORTERM": "truecolor",
  "CommonProgramFiles": "C:\\Program Files\\Common Files",
  "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
  "CommonProgramW6432": "C:\\Program Files\\Common Files",
  "COMPUTERNAME": "DEEP",
  "ComSpec": "C:\\Windows\\system32\\cmd.exe",
  "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
  "EDITOR": "notepad.exe",
  "FPS_BROWSER_APP_PROFILE_STRING": "Internet Explorer",
  "FPS_BROWSER_USER_PROFILE_STRING": "Default",
  "GIT_ASKPASS": "c:\\Users\\Deep1\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh",
  "GPU_FORCE_64BIT_PTR": "0",
  "GPU_MAX_ALLOC_PERCENT": "100",
  "GPU_MAX_HEAP_SIZE": "100",
  "GPU_SINGLE_ALLOC_PERCENT": "100",
  "GPU_USE_SYNC_OBJECTS": "1",
  "HOME": "C:\\Users\\Deep1",
  "HOMEDRIVE": "C:",
  "HOMEPATH": "\\Users\\Deep1",
  "INIT_CWD": "E:\\Git hub projects\\clone_react\\Netflix-Clone",
  "LANG": "en_US.UTF-8",
  "LOCALAPPDATA": "C:\\Users\\Deep1\\AppData\\Local",
  "LOGONSERVER": "\\\\DEEP",
  "NODE": "C:\\Program Files\\nodejs\\node.exe",
  "NODE_EXE": "C:\\Program Files\\nodejs\\\\node.exe",
  "NPM_CLI_JS": "C:\\Program Files\\nodejs\\\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_command": "run-script",
  "npm_config_cache": "C:\\Users\\Deep1\\AppData\\Local\\npm-cache",
  "npm_config_globalconfig": "C:\\Users\\Deep1\\AppData\\Roaming\\npm\\etc\\npmrc",
  "npm_config_global_prefix": "C:\\Users\\Deep1\\AppData\\Roaming\\npm",
  "npm_config_init_module": "C:\\Users\\Deep1\\.npm-init.js",
  "npm_config_local_prefix": "E:\\Git hub projects\\clone_react\\Netflix-Clone",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "npm_config_node_gyp": "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js",
  "npm_config_noproxy": "",
  "npm_config_prefix": "C:\\Users\\Deep1\\AppData\\Roaming\\npm",
  "npm_config_userconfig": "C:\\Users\\Deep1\\.npmrc",
  "npm_config_user_agent": "npm/8.1.2 node/v16.13.2 win32 x64 workspaces/false",
  "npm_execpath": "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_lifecycle_event": "build",
  "npm_lifecycle_script": "react-dotenv && react-scripts build",
  "npm_node_execpath": "C:\\Program Files\\nodejs\\node.exe",
  "npm_package_json": "E:\\Git hub projects\\clone_react\\Netflix-Clone\\package.json",
  "npm_package_name": "netflixclone",
  "npm_package_version": "0.1.0",
  "NPM_PREFIX_NPM_CLI_JS": "C:\\Users\\Deep1\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
  "NUMBER_OF_PROCESSORS": "8",
  "OneDrive": "C:\\Users\\Deep1\\OneDrive",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "OS": "Windows_NT",
  "Path": "E:\\Git hub projects\\clone_react\\Netflix-Clone\\node_modules\\.bin;E:\\Git hub projects\\clone_react\\node_modules\\.bin;E:\\Git hub projects\\node_modules\\.bin;E:\\node_modules\\.bin;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;E:\\Git hub projects\\clone_react\\Netflix-Clone\\node_modules\\.bin;E:\\Git hub projects\\clone_react\\node_modules\\.bin;E:\\Git hub projects\\node_modules\\.bin;E:\\node_modules\\.bin;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\Program Files\\Common Files\\Oracle\\Java\\javapath;C:\\python;E:\\Python\\Scripts\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Users\\Deep1\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\JetBrains\\PyCharm Community Edition 2020.2.3\\bin;C:\\adb;C:\\Git\\cmd;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\nodejs\\;C:\\ProgramData\\chocolatey\\bin;C:\\Users\\Deep1\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\;C:\\Users\\Deep1\\AppData\\Local\\Programs\\Python\\Python39\\;C:\\Users\\Deep1\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\JetBrains\\PyCharm Community Edition 2020.3.1\\bin;C:\\Program Files\\JetBrains\\PyCharm 2020.3\\bin;C:\\python;C:\\python\\Scripts;C:\\Users\\Deep1\\AppData\\Local\\GitHubDesktop\\bin;C:\\Users\\Deep1\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Program Files\\Java\\jdk-17.0.1\\bin;C:\\dart-sdk\\bin;C:\\Program Files\\MongoDB\\Server\\5.0\\bin;C:\\Users\\Deep1\\AppData\\Roaming\\npm;C:\\Program Files (x86)\\flutter\\bin;C:\\Users\\Deep1\\Desktop\\flutter\\bin;C:\\platform-tools;",
  "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL",
  "PROCESSOR_ARCHITECTURE": "AMD64",
  "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 142 Stepping 11, GenuineIntel",
  "PROCESSOR_LEVEL": "6",
  "PROCESSOR_REVISION": "8e0b",
  "ProgramData": "C:\\ProgramData",
  "ProgramFiles": "C:\\Program Files",
  "ProgramFiles(x86)": "C:\\Program Files (x86)",
  "ProgramW6432": "C:\\Program Files",
  "PROMPT": "$P$G",
  "PSModulePath": "C:\\Users\\Deep1\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
  "PUBLIC": "C:\\Users\\Public",
  "PyCharm": "C:\\Program Files\\JetBrains\\PyCharm 2020.3\\bin;",
  "PyCharm Community Edition": "C:\\Program Files\\JetBrains\\PyCharm Community Edition 2020.3.1\\bin;",
  "SESSIONNAME": "Console",
  "SystemDrive": "C:",
  "SystemRoot": "C:\\Windows",
  "TEMP": "C:\\Users\\Deep1\\AppData\\Local\\Temp",
  "TERM_PROGRAM": "vscode",
  "TERM_PROGRAM_VERSION": "1.66.2",
  "TMP": "C:\\Users\\Deep1\\AppData\\Local\\Temp",
  "USERDOMAIN": "DEEP",
  "USERDOMAIN_ROAMINGPROFILE": "DEEP",
  "USERNAME": "Deep1",
  "USERPROFILE": "C:\\Users\\Deep1",
  "VBOX_MSI_INSTALL_PATH": "C:\\Program Files\\Oracle\\VirtualBox\\",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "--ms-enable-electron-run-as-node",
  "VSCODE_GIT_ASKPASS_MAIN": "c:\\Users\\Deep1\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js",
  "VSCODE_GIT_ASKPASS_NODE": "C:\\Users\\Deep1\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe",
  "VSCODE_GIT_IPC_HANDLE": "\\\\.\\pipe\\vscode-git-0278fa8755-sock",
  "windir": "C:\\Windows"
};